# Delivery pipeline config
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my_del_pip
  labels:
    app: cicd
description: Configuration of the delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
  - targetId: prod

# Target config
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: App Deployment in development environment
gke:
  cluster: projects/gke-test/locations/europe-west1/clusters/my_dev_cluster

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: App Deployment in production environment
requireApproval: true
gke:
  cluster: projects/gke-test/locations/europe-west1/clusters/my_prd_cluster
