# Deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-for-app-greetings
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-greetings
  template:
    metadata:
      labels:
        app: my-app-greetings
    spec:
      containers:
      - name: my-container
        image: europe-west1-docker.pkg.dev/gke-test-422915/my-repo/flask-image
        ports:
          - containerPort: 8081

# Service config
apiVersion: v1
kind: Service
metadata:
  name: my-service-for-app-greetings
spec:
  selector:
    app: my-app-greetings
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
